<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_CsMultiSellerImportExport
 * @author    CedCommerce Core Team <connect@cedcommerce.com >
 * @copyright Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
?>
<?php
/** @var $block \Ced\CsMultiSellerImportExport\Block\Import\Edit\Before */
$headers = $block->getHeaders();
?>
<script>
    require([
        'Ced_CsMultiSellerImportExport/js/import/vendor'
    ], function(VendorImport) {
        vendorImport = VendorImport;
        vendorImport.init({
            urlBack: '<?php /* @escapeNotVerified */ echo $block->getBackUrl(); ?>',
            urlExportCsv: '<?php /* @escapeNotVerified */ echo $block->getExportCsvUrl(); ?>',
            urlUpload: '<?php /* @escapeNotVerified */ echo $block->getFileUploadUrl(); ?>',
            urlDelete: '<?php /* @escapeNotVerified */ echo $block->getFileDeleteUrl(); ?>',
            urlValidate: '<?php /* @escapeNotVerified */ echo $block->getValidateUrl(); ?>',
            urlImport: '<?php /* @escapeNotVerified */ echo $block->getImportUrl(); ?>',
            urlRedirect: '<?php /* @escapeNotVerified */ echo $block->getRedirectUrl(); ?>',
            maxFileSize: <?php /* @escapeNotVerified */ echo $block->getMaxSize(); ?>,
            headers: <?php /* @escapeNotVerified */ echo $block->jsonEncodeData($headers); ?>,
        });
    });
</script>
